[42기 박준현] Feature/checkout , 체크 아웃 컴포넌트 구현
wecode-bootcamp-korea/42-1st-GarbageCollector-frontend pull request #14
Opened 2023-02-15 13:20 UTC by jhp4986

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [x] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.
- 장바구니에서 넘어오는 상품 데이터 받을 수 있는 리스트 구현 
- 배송지 입력 버튼 눌렀을때 모달창 띄우고 모달창에서 적은 데이터 주문서 페이지에 입력 
- 주문금액 -상품 할인 + 배송비 + 총결제금액 우측 정리된 화면 결제 하기 버튼 만들기

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 배송지 등록 하는 버튼을 눌렀을때, 모달창을 띄우고 모달창에 유저 이름 연락처 배송지 등을 입력을 하고 그 입력한 데이터를 모달창 띄우기 이전 주문서 페이지에 데이터가 입력이 될수 있게끔 구현 하는 것에 신경을 많이 썼습니다.. 처음 써보는 모달 창이었고, 어떻게 해야하는지 조금 막막했지만, 구글링을 하면서 이거저거 시도 해보면서 성공했습니다. 

<br />

## :: 기타 질문 및 특이 사항

2023-02-16 05:37 UTC, hani2525 requested changes
고생하셨습니다 준현님!
리뷰 반영은 아래 참고사항 고려하셔서 고쳐주시면 됩니다.

✅  리팩토링 참고 사항
🔴  지금 당장 고쳐야 할 코드

2023-02-16 05:37 UTC, hani2525 commented on src/pages/Checkout/Checkout.js
> +  //
🔴  
쓰지 않는 주석은 삭제해주세요!

2023-02-16 05:37 UTC, hani2525 commented on src/pages/Checkout/Checkout.js
> +                  <div key={index}>
🔴 
map돌릴 때 key값을 배열 요소의 index로 부여하면 안됩니다~ 요소에 있는 데이터 중 유일한 값을 부여해주세요!

2023-02-16 05:37 UTC, hani2525 commented on src/pages/Checkout/Checkout.js
> +                  style={{ display: userInfo.length > 0 ? 'none' : 'block' }}
✅ 

- 리뷰내용
    - 인라인 스타일 사용은 반드시 필요한 경우가 아니면 지양해주세요
    1. 우선순위가 !important 제외하고 가장 높게 적용됨
    2. css관련 로직이 css 파일이 아닌 html에 있어서 유지보수하기 좋지않음
    - 위 이유들로 인해서 반드시 필요한 경우가 아닌 한 인라인 스타일은 지양해주세요

2023-02-16 05:37 UTC, hani2525 commented on src/pages/Checkout/Checkout.js
> +              <span> : ({productList[0]?.userPoint} point) </span>
🔴 

`{productList[0]?.userPoint}`  이 부분 변수로 선언하신 다음에 쓰시는게 좋을 것 같습니다.

2023-02-16 05:37 UTC, hani2525 commented on src/pages/Checkout/Checkout.js
> +                name={productList[0]?.cartId}
🔴 

이 부분도 변수로 선언하신 후에 사용해주세요.

2023-02-16 05:37 UTC, hani2525 commented on src/pages/Checkout/UserInfo.js
> +      </div>
✅ 

해당 부분 컴포넌트화 및 반복문을 통해 UI를 관리하시면 더 깔끔하고 유지보수가 쉬운 코드를 짤 수 있을 것 같아요!
리팩토링 기간 때 한 번 연습해봅시다!

2023-02-16 08:34 UTC, jhp4986 commented on src/pages/Checkout/Checkout.js
> +  //
수정했습니다, 감사합니다

2023-02-16 08:41 UTC, jhp4986 commented on src/pages/Checkout/Checkout.js
> +                  <div key={index}>
수정했습니다 !

2023-02-16 08:54 UTC, jhp4986 commented on src/pages/Checkout/Checkout.js
> +                  <div key={index}>
수정완료 감사합니다 !

2023-02-16 09:09 UTC, jhp4986 commented on src/pages/Checkout/Checkout.js
> +              <span> : ({productList[0]?.userPoint} point) </span>
수정완료 했습니다 !

2023-02-16 09:11 UTC, jhp4986 commented on src/pages/Checkout/Checkout.js
> +                name={productList[0]?.cartId}
수정했습니다

2023-02-16 09:13 UTC, jhp4986 commented on src/pages/Checkout/UserInfo.js
> +      </div>
넵 !

2023-02-17 02:02 UTC, hani2525 approved these changes

2023-02-17 02:02 UTC, merged