[42기 박준현] add: 주문완료 페이지 구현 완료
wecode-bootcamp-korea/42-1st-GarbageCollector-frontend pull request #17
Opened 2023-02-16 07:26 UTC by jhp4986

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
주문서 페이지에서 결제 하기 버튼을 눌러서 넘어오는 주문완료 페이지 구현 

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
주문서 페이지에서 주문한 상품 밑 주문자 이름 주소 등 받아오는 리스트 구현 

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)

<br />

## :: 기타 질문 및 특이 사항

2023-02-16 07:31 UTC, hani2525 requested changes
준현님! 리뷰 확인해주세요.
리뷰 반영은 아래 마크 참고하시면 됩니다.

🔴  지금 당장 바꿔야 할 코드
✅  리팩토링 참고 사항

2023-02-16 07:31 UTC, hani2525 commented on src/pages/Ordered/Ordered.js
> +              주문번호 : {productList[0]?.orderNumber}
🔴 
`{productList[0]?.orderNumber}` 이 부분 위에서 변수에 할당한 후 사용해주세요!

2023-02-16 07:31 UTC, hani2525 commented on src/pages/Ordered/Ordered.js
> +                  {productList[0]?.productName}
🔴 
productList[0]에서 사용하는 데이터가 많네요.
위에서 변수 선언부쪽에서 구조분해할당한 후 사용하시면 좋을 것 같습니다.

2023-02-16 07:31 UTC, hani2525 commented on src/pages/Ordered/Ordered.js
> +                배송지 :{' '}
🔴 
사용하지 않는 공백은 지워주세요!

2023-02-16 09:20 UTC, jhp4986 commented on src/pages/Ordered/Ordered.js
> +                배송지 :{' '}
수정했습니다 !

2023-02-16 09:27 UTC, jhp4986 commented on src/pages/Ordered/Ordered.js
> +              주문번호 : {productList[0]?.orderNumber}
수정 했습니다 !

2023-02-16 09:28 UTC, jhp4986 commented on src/pages/Ordered/Ordered.js
> +                  {productList[0]?.productName}
수정했습니다 !

2023-02-17 02:02 UTC, hani2525 approved these changes

2023-02-17 02:02 UTC, merged