[42기 이동민] Add: 로그인 컴포넌트 필수 구현 사항 구현
wecode-bootcamp-korea/42-1st-GarbageCollector-frontend pull request #2
Opened 2023-02-08 06:57 UTC by gmgmgun

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 아이디, 비밀번호 입력창을 사용한 로그인 기능 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. input 요소에 입력된 정보의 유효성 검사 후 로그인 버튼 활성화
- ID/PW 값이 null이 아닌 경우 버튼 활성화.

2. 로그인 버튼 onClick 이벤트 발생 시 token 값 기준으로 처리 분기 

3. placeholder를 label로 대체.
- input 요소가 focus될 경우 라벨 크기 및 위치 변경

4. input 요소 blur 시 값이 null이면
- 요소 하단에 경고 문구 출력
- 요소 테두리 및 라벨 색 변경 

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- label을 사용하면서 label의 쓰임새에 대해 알 수 있었습니다.
- 특정 요소의 이벤트 핸들러에서 형제 요소의 값을 참조하는 방법에 대해 새로 알게 되었습니다.

<br />

## :: 기타 질문 및 특이 사항
- isIdEmpty / isPwEmpty를 state를 통해 같이 관리할 수 있는지 궁금합니다. 가능은 할 것으로 보이나 구조가 복잡해보입니다.
- 로그인 컴포넌트 내 기능 중 추가 구현 사항은 아이디 저장 기능 / 아이디 및 비밀번호 찾기 기능 / 비회원 주문 조회 기능 / 로그인 실패 시 modal로 alert 입니다.

2023-02-08 07:56 UTC, hani2525 commented
isIdEmpty, isPwEmpty를 같은 state로 관리할 수는 있습니다. 하지만 굳이 state를 따로 만들어서 관리할 필요는 없어보입니다.

2023-02-08 07:56 UTC, hani2525 requested changes
동민님 고생 많으셨습니다! 리뷰 반영 후 push 올리시고 '멘토 리뷰 요청'태그로 변경해주세요!

2023-02-08 07:56 UTC, hani2525 commented on src/pages/Login/Login.js
> +              placeholder=" "
placeholder에 빈 값을 주지 않을 때와 placeholder 속성을 아예 사용하지 않는 것과 차이가 있나요? 차이가 없으면 굳이 사용하지 않으셔도 됩니다.

2023-02-08 07:56 UTC, hani2525 commented on src/pages/Login/Login.js
> +    // 서버와 통신 시
주석을 작성하실 때 추후에 추가로 작성하거나 수정해야 하는 경우

//TODO:
//TOFIX: or FIXME:

이렇게 주석에 표시를 달아주고 사용하는 것이 일반적입니다.
그냥 주석을 쓰게 되면 어떤 주석인지 파악이 어려울 수 있습니다.

지금 작성하신 주석은 서버 통신할 때 다시 살릴 코드니
//TODO: API 연결 시 동작할 코드 

이런 식으로 표시해두시면 좋을 것 같습니다.

2023-02-08 07:56 UTC, hani2525 commented on src/pages/Login/Login.scss
> +/* stylelint-disable max-nesting-depth */
사용하지 않는 주석은 삭제해주세요.

2023-02-08 07:56 UTC, hani2525 commented on src/pages/Login/Login.scss
> +          -webkit-appearance: none;
css속성을 부여할 때 비슷한 속성끼리는 묶어주시는게 좋습니다.
-webkit , -moz관련된 속성은 비슷한 위치에 작성해주세요!,

2023-02-09 23:24 UTC, gmgmgun commented on src/pages/Login/Login.js
> +              placeholder=" "
placeholder 속성을 사용하지 않으면 placeholder-shown이라는 가상 선택자가 적용되지 않아서 사용하게 되었습니다!

2023-02-09 23:25 UTC, gmgmgun commented on src/pages/Login/Login.js
> +    // 서버와 통신 시
수정 반영하겠습니다. 감사합니다!

2023-02-09 23:28 UTC, gmgmgun commented on src/pages/Login/Login.scss
> +/* stylelint-disable max-nesting-depth */
detph 3을 초과해서 네스팅할 시 스타일린트 컨벤션으로 에러가 얼럿되는데 3 이하로 네스팅이 어려워 얼럿 방지용으로 넣어놨습니다 ㅜ.ㅜ 어떻게 하면 좋을까요 ㅜㅜ

2023-02-09 23:28 UTC, gmgmgun commented on src/pages/Login/Login.scss
> +          -webkit-appearance: none;
넵 수정하겠습니다!

2023-02-10 07:03 UTC, hani2525 reviewed
동민님 추가 리뷰 확인해주세요!

2023-02-10 07:03 UTC, ghost commented on src/pages/Login/Login.scss
> +/* stylelint-disable max-nesting-depth */
stylelint에서 기본적으로 컨벤션을 작성해뒀는데 커스텀할 수 있습니다! 

- [.stylelintrc.json 사용법](https://nanpokongyee.tistory.com/7)

2023-02-13 07:58 UTC, hani2525 requested changes
동민님 리뷰 확인 후 반영해주세요~

2023-02-13 07:58 UTC, hani2525 commented on src/pages/Login/Login.js
> +  // };
불필요한 주석은 삭제해주세요!
코드가 주석처리된 채로 남아있다면 필요한 상황에 제대로 사용되거나 삭제되는 일은 거의 없고 결국 계속 남아있게 됩니다.
그러다보면 이제 작성한 사람이 아닌 다른 개발자는 필요한 코드라서 주석처리한게 아닐까? 라는 생각으로 지우지 못하고
결국 그 누구도 왜 있는지는 모르면서 계속 남아있는 불필요한 레거시가 되어버립니다!
따라서 반드시 필요한 경우가 아니면 코드를 주석처리하기보다는 삭제해주시고 만약 다시 보고싶다면 커밋 이력에 잘 남겨뒀다가 원하는 시점에 다시 보면 됩니다!

2023-02-14 05:06 UTC, hani2525 approved these changes
동민님 고생하셨습니다!

2023-02-14 05:06 UTC, merged