[42기 이해인 ]ADD:통신연결했으나, CSS깨짐
wecode-bootcamp-korea/42-1st-GarbageCollector-frontend pull request #5
Opened 2023-02-10 10:52 UTC by heinlee4680

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 상품리스트를 가지고 있는 API와 통신연결함

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
백엔드 상품list API 와 연결하여 원래 구상하려던 것과 유사하게 잘 나오는지 시도해봄.
-> CSS가 깨져서 원하는대로 안보임
-> 상품 Lsit 데이터가조금 구성되면 다시 CSS잡겠습니다.

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- > 통신을연결하는데에 두번째다보니 쉽지 않아 조금 어려웠으나, 극복했습니다. 

<br />

## :: 기타 질문 및 특이 사항
- > 연결하는 로직..? 을 외워야하는지.. 이번에는위스타그램에서 했던것을 참고했는데 외워야할까요. ?

2023-02-13 02:39 UTC, hani2525 requested changes
해인님 고생하셨습니다 리뷰 확인 후 반영해주세요!

2023-02-13 02:39 UTC, hani2525 commented on src/pages/ProductDetail/ProductOrderModal.js
> +    setProductQuantity(productQuantity - 1);
setState  함수의 인자로는 

1. 새로운 state가 될 값
2. 콜백함수

두가지 유형의 인자를 전달할 수 있습니다.
콜백함수를 인자로 전달한다면 콜백함수는 인자로 이전의 state값을 전달받고 함수에서 return 한 값이 새로운 state가 됩니다!

- 이전 state 값을 명시적으로 기억할 필요가 없음
- 함수가 호출될 당시 최신의 state값이 인자로 전달되므로 비동기 상황에서 안정적

위와 같은 이유들로 인해 이전 state 값을 이용해서 새로운 state값을 만드는 경우에는 콜백함수를 인자로 전달하는방식으로  적용해주세요

아래코드 참고해보세요

```jsx
setState(newState); // 1. 새로운 state가 될 값을 인자로 전달하는 경우
setState(prevState => newState); // 2. callback함수를 인자로 전달하는 경우

//
const [count, setCount] = useState(0);

// ver.1
const increaseCount = () => setCount(count + 1);

// ver2.
const increaseCount = () => setCount(prevCount => prevCount + 1);
```

2023-02-13 02:39 UTC, hani2525 commented on src/pages/ProductDetail/ProductOrderModal.js
> +        </p>
가격이라는 문구를 화면에 보여주는거면 p태그로 감싸줄 필요 없이 span태그 하나만 사용해도 될 것 같습니다.

2023-02-13 02:40 UTC, hani2525 commented
연결하는 로직이 백엔드와 통신하는 로직을 말씀하시는건가요~?

2023-02-14 15:29 UTC, heinlee4680 commented on src/pages/ProductDetail/ProductOrderModal.js
> +        </p>
이 컴포넌트는 다른 브랜치에서 편집해서 여기서는 지우겠습니당 ㅠ_ㅠ

2023-02-15 05:46 UTC, hani2525 approved these changes

2023-02-15 05:47 UTC, merged