[42기 이해인]Feature/product detail
wecode-bootcamp-korea/42-1st-GarbageCollector-frontend pull request #6
Opened 2023-02-13 02:24 UTC by heinlee4680

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 상세페이지 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 상품 데이터를 받아와서 그 데이터에  옵션이 있는경우, 옵션을 선택했을때 오더 리스트 구현 

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 옵션을 선택했을때 오더 리스트는 구현이 되나, 데이터가 교체가 되어 해결이 안되는 상황입니다. 

<br />

## :: 기타 질문 및 특이 사항
- 이정일 멘토님께 접근방법에 대해 여쭤본 상황이라 코드 리뷰를 위해 올렸습니다.

2023-02-14 03:09 UTC, hani2525 requested changes
해인님! 고생하셨습니다 리뷰 반영해주세요!

2023-02-14 03:09 UTC, hani2525 commented on src/pages/ProductDetail/ProductDetail.js
> +  // const [orderItemList, setOrderItemList] = useState([]);
불필요한 주석은 삭제해주세요!
코드가 주석처리된 채로 남아있다면 필요한 상황에 제대로 사용되거나 삭제되는 일은 거의 없고 결국 계속 남아있게 됩니다.
그러다보면 이제 작성한 사람이 아닌 다른 개발자는 필요한 코드라서 주석처리한게 아닐까? 라는 생각으로 지우지 못하고
결국 그 누구도 왜 있는지는 모르면서 계속 남아있는 불필요한 레거시가 되어버립니다!
따라서 반드시 필요한 경우가 아니면 코드를 주석처리하기보다는 삭제해주시고 만약 다시 보고싶다면 커밋 이력에 잘 남겨뒀다가 원하는 시점에 다시 보면 됩니다!

2023-02-14 03:09 UTC, hani2525 commented on src/pages/ProductDetail/ProductDetail.js
> +  // };
여기도 마찬가지로 주석은 삭제해주세요!

2023-02-14 03:09 UTC, hani2525 commented on src/pages/ProductDetail/ProductDetail.js
> +                    // handleOption={handleOption}
주석 삭제해주세요~

2023-02-14 03:09 UTC, hani2525 commented on src/pages/ProductDetail/ProductDetail.js
> +              {/* {console.log(option.id)} */}
주석 및 console.log는 삭제해주세요~

2023-02-14 03:09 UTC, hani2525 commented on src/pages/ProductDetail/ProductDetail.js
> +                ) : null;
굳이 삼항연산자로 true, false 케이스 모두 처리하여 null을 반환할 필요없이 이 부분은 true 케이스만 처리하면 되기 때문에 조건부 렌더링 (`&&` 연산자)을 활용하면 불필요한 코드를 없애 더욱 가독성에 좋아집니다. 

- 참고 : 공식문서 조건부 렌더링([https://ko.reactjs.org/docs/conditional-rendering.html](https://ko.reactjs.org/docs/conditional-rendering.html))

```jsx
true ? foo : null => true && foo // true인 경우에 foo 요소를 렌더
```

2023-02-14 03:09 UTC, hani2525 commented on src/pages/ProductDetail/ProductDetail.js
> +            </section>
감싸주는 태그가 너무 많은 것 같은데 전부 다 필요한 태그들인가요?

2023-02-14 03:09 UTC, hani2525 commented on src/pages/ProductDetail/ProductDetail.scss
> +      // border: 1px solid violet;
주석 삭제해주세요!

2023-02-14 03:09 UTC, hani2525 commented on src/pages/ProductDetail/ProductDetail.scss
> +/* stylelint-disable max-nesting-depth */
주석 삭제해주세요! stylelint관련된 에러로 인한 주석이라면
stylelintrc.json을 수정하시면 됩니다!

- [stylelintrc.json 사용법](https://nanpokongyee.tistory.com/7)

2023-02-14 03:09 UTC, hani2525 commented on src/pages/ProductDetail/ProductDetail.scss
> +              padding: 0 27px 0 0;
padding의 값을 한 쪽에만 부여하고 싶을 땐 shorhand property를 사용하지 않으셔도 됩니다.
 `padding-right:27px;` 만 작성하셔도 됩니다.

2023-02-14 03:09 UTC, hani2525 commented on src/pages/ProductDetail/ProductOrderModal.js
> +  // };
불필요한 주석은 삭제해주세요!
코드가 주석처리된 채로 남아있다면 필요한 상황에 제대로 사용되거나 삭제되는 일은 거의 없고 결국 계속 남아있게 됩니다.
그러다보면 이제 작성한 사람이 아닌 다른 개발자는 필요한 코드라서 주석처리한게 아닐까? 라는 생각으로 지우지 못하고
결국 그 누구도 왜 있는지는 모르면서 계속 남아있는 불필요한 레거시가 되어버립니다!
따라서 반드시 필요한 경우가 아니면 코드를 주석처리하기보다는 삭제해주시고 만약 다시 보고싶다면 커밋 이력에 잘 남겨뒀다가 원하는 시점에 다시 보면 됩니다!

2023-02-14 04:18 UTC, heinlee4680 commented on src/pages/ProductDetail/ProductDetail.js
> +  // const [orderItemList, setOrderItemList] = useState([]);
아하!!! 
넹 알겠습니당!!

2023-02-14 15:57 UTC, heinlee4680 commented on src/pages/ProductDetail/ProductDetail.scss
> +/* stylelint-disable max-nesting-depth */
넹!

2023-02-15 06:03 UTC, hani2525 approved these changes
고생하셨습니다 해인님!
ProductDetail 폴더에 있는 컴포넌트 안에 코드를 살펴보면
컴포넌트 및 반복문을 통해 UI를 관리할 수 있는 부분이 꽤 많이 보여요.
리팩토링 기간에 꼭 한 번 연습해보시면 많은 도움이 될 것 같습니다.

코드 리뷰는 아래 마크를 참고하시고 반영하시면 됩니다.

✅ 리팩토링 참고 사항
🔴 지금 당장 고쳐야 할 코드

2023-02-15 06:03 UTC, ghost commented on src/pages/ProductDetail/ProductBasicInfo.js
> +      </div>
✅ 

해당 부분도 반복문 및 컴포넌트를 통해 UI를 관리하는 법을 생각해보시면 좋을 것 같습니다.

2023-02-15 06:03 UTC, hani2525 commented
해인님 merge conflict resolve만 해주세요~

2023-02-15 06:29 UTC, merged