[42기 이동민]  Add: Carousel 컴포넌트 추가
wecode-bootcamp-korea/42-1st-GarbageCollector-frontend pull request #8
Opened 2023-02-13 13:45 UTC by gmgmgun

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 캐러셀을 이용한 이미지 슬라이드 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. tranlateX 속성을 이용해 슬라이드 기능 구현

2. 무한 슬라이드 기능 구현
- index를 계산하여 index가 0 or length-1일 경우 분기 처리
- 양 끝 슬라이드를 복제해 배열에 넣어 현재 보여주는 인덱스가 복제 슬라이드의 인덱스인 경우, (1)setTimeout을 걸음.
(2)setTimeout의 콜백에서 transition 값을 0으로 변경하여 애니메이션 효과 없앰.
(3)원본의 슬라이드의 인덱스로 set.(0일 경우 마지막 인덱스, length-1일 경우 첫번째 인덱스)
(4)자동 슬라이드의 경우 (2)에 의해 transition이 0으로 초기화되는 상황을 방지하기 위해 setTimeout을 걸어 1로 바꿔줌.

3. 자동 슬라이드 기능 구현
-setInterval을 이용해 4초에 한번씩 슬라이드를 변경해줌.

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- setTimeout을 통해 비동기 처리하는 법을 배웠습니다.

<br />

## :: 기타 질문 및 특이 사항
- 슬라이드 배열을 map으로 돌릴 경우 복제된 슬라이드 때문에 mock 데이터의 id를 map의 키값으로 쓸 수 없었습니다. 슬라이드를 복제할 때 깊은 복사를 하고 id값을 바꿔주면 가능할 것 같은데 객체를 깊은 복사하는 방법이 있는지 궁금합니다.

2023-02-14 03:27 UTC, hani2525 requested changes
동민님 고생하셨습니다! 리뷰 확인해주시고 반영해주세요!

2023-02-14 03:27 UTC, hani2525 commented on src/Router.js
> +// import Main from './pages/Main/Main';
주석은 삭제해주세요!

2023-02-14 03:27 UTC, hani2525 commented on src/Router.js
> +        {/* <Route path="/" element={<Main />} /> */}
마찬가지로 주석은 삭제해주세요!

2023-02-14 03:27 UTC, hani2525 commented on src/components/Carousel/Carousel.js
> +        setSlideList(data);
data를 꼭 두 개의 상태에서 관리해야하는 이유가 뭔가요~?

2023-02-14 03:27 UTC, hani2525 commented on src/components/Carousel/Carousel.js
> +          <img key={idx} alt={slide.alt} src={slide.src} />
React에서 map 함수를 통한 rendering시에 key prop이 필요한 이유는 react가 리렌더시에 key prop을 통해서 이전 결과와 현재 결과에서 변경되어야 하는 부분을 파악해서 실질적으로 변화가 생겨야하는 부분만 효율적으로 리렌더링 하기 위함입니다.

즉, Key값을 부여하는 이유와 Key값에 사용되어야 하는 값은 아래와 같습니다.

1. React의 re-render시에 효율성을 위해서 key값을 부여해야 한다.
2. index값은 배열의 요소가 어디에 추가되느냐에 따라서 가변적일 수 있기에 해당 요소가 가지고 있는 **"특정하고 유일한 값"**을 이용하는 것이 권장됩니다

만약 아래와 같은 리스트가 있는데 제일 처음에 `<li>0</li>`을 추가해야 되는 상황일때

```
<ul>
  <li>1</li>
  <li>2</li>
  <li>3</li>
  <li>4</li>
</ul>

```

⬇

```
<ul>
  <li>0</li>
  <li>1</li>
  <li>2</li>
  <li>3</li>
  <li>4</li>
</ul>

```

key 값이 부여 안됬을 경우에는 리엑트에서 0~5까지의 모든 li를 다시 렌더링하게 됩니다.
하지만 key값이 부여되었을 경우에는

```
<ul>
  <li key={1}>1</li>
  <li key={2}>2</li>
  <li key={3}>3</li>
  <li key={4}>4</li>
</ul>

```

⬇️

```
<ul>
  <li key={0}>0</li>
  <li key={1}>1</li>
  <li key={2}>2</li>
  <li key={3}>3</li>
  <li key={4}>4</li>
</ul>

```

key값을 토대로 react가 1~4까지는 기존의 렌더된 DOM 구성요소와 동일하다고 판단하고 `<li key={0}>0</li>` 만 추가적으로 렌더링하게 되어서

렌더시의 효율이 올라가게 됩니다.
이러한 이유로 map을 사용해서 렌더링을 할때는 효율성을 위해서 반드시 key값을 부여해줘야 합니다.
추가적으로 index값은 배열에 요소가 어디에 추가되느냐에 따라서 변할 수 있기 때문에 key값으로 사용하는 것은 권장되지 않습니다.

2023-02-14 03:27 UTC, hani2525 commented on src/components/Carousel/Carousel.scss
> +    background-color: transparent;
- 하나의 요소에 여러가지 속성을 부여하는 경우 중요도, 관련도에 따라 나름의 convention을 지켜서 작성하는 것이 좋습니다.
- 일반적인 convention 은 아래와 같습니다. 아래와 같이 순서 적용해주세요.
    
    [CSS property 순서]
    
    - Layout Properties (position, float, clear, display)
    - Box Model Properties (width, height, margin, padding)
    - Visual Properties (color, background, border, box-shadow)
    - Typography Properties (font-size, font-family, text-align, text-transform)
    - Misc Properties (cursor, overflow, z-index)

2023-02-14 04:17 UTC, gmgmgun commented on src/Router.js
> +// import Main from './pages/Main/Main';
넵 알겠습니다!

2023-02-14 04:17 UTC, gmgmgun commented on src/Router.js
> +        {/* <Route path="/" element={<Main />} /> */}
넵 알겠습니다!

2023-02-14 05:01 UTC, gmgmgun commented on src/components/Carousel/Carousel.js
> +        setSlideList(data);
slideList의 경우 슬라이드 변환을 자연스럽게 하기 위해 배열 양 끝에 복사한 객체를 새로 추가해 배열에 변형이 일어납니다.
그런데 버튼 클릭 시 해당 배열의 요소의 값을 기준으로 하여 해당 슬라이드로 이동을 하는데 이미 slideList는 복사한 객체로 인해 변형이 일어난 상태라 요소 값 기준으로 하게 되면 복사한 객체와 값이 중복되기 때문에 원본 배열을 저장하기 위해 상태를 두개를 사용했습니다!

2023-02-14 05:05 UTC, gmgmgun commented on src/components/Carousel/Carousel.js
> +          <img key={idx} alt={slide.alt} src={slide.src} />
map key 값에 배열의 index 사용을 최대한 지양하려고 했는데요 ..ㅜㅜ
기타 질문 및 특이사항에 작성드린 것처럼 복사한 객체의 id를 변경할 수 있는 방법을 찾지 못해 부득이하게 index를 사용하게 되었습니다... 혹시 다른 방법이 있을까요?

2023-02-14 05:06 UTC, gmgmgun commented on src/components/Carousel/Carousel.scss
> +    background-color: transparent;
넵 수정하겠습니다!!

2023-02-14 05:07 UTC, gmgmgun commented on src/components/Carousel/Carousel.scss
> +    background-color: transparent;
스타일린트가 자동적으로 상기와 같이 정렬해버리네요 ㅜㅜ

2023-02-14 06:14 UTC, hani2525 commented on src/components/Carousel/Carousel.js
> +          <img key={idx} alt={slide.alt} src={slide.src} />
key에는 id값이 아니더라도 데이터의 고유한 값이면 됩니다!

{
'name': 'gildong',
'phoneNum': '01012345678'
}

이렇게 있을 때, phoneNum(핸드폰 번호)가 유일한 값이면 key 값으로 쓰셔도 됩니다!

2023-02-14 06:16 UTC, hani2525 commented on src/components/Carousel/Carousel.scss
> +    background-color: transparent;
css convention은 정해진게 아니라서 팀 내에서 정해진 convention에만 따르면 됩니다.
제가 보여드린 예시는 위코드에서 일반적으로 사용하고 있는 css convention이니 꼭 따르실 필요는 없어용~

2023-02-14 06:16 UTC, hani2525 requested changes
동민님! Key 값만 수정해주시면 될 것 같습니다! 화이팅!

2023-02-15 05:46 UTC, hani2525 approved these changes

2023-02-15 05:46 UTC, merged